name: CI

on:
  push

jobs:
  qa-unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.8.2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8' 
          cache: 'poetry'
      - name: Install the project dependencies
        run: poetry install
      - name: Black QA
        run: poetry run black . --check
      - name: Pytest
        run: poetry run pytest

  build-windows:
    runs-on: windows-latest
    needs: qa-unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.8.2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8' 
          cache: 'poetry'
      - name: Install the project dependencies
        run: poetry install
      - name: Downlowd upx
        run: |
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip" -OutFile "upx.zip"
          Expand-Archive -Path "upx.zip" -DestinationPath "."
      - name: Package application for Windows
        run: poetry run pyinstaller --onefile --name=my_app --upx-dir='.\upx-4.2.2-win64' main.py
      - name: Upload artifact main
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/*
          if-no-files-found: error
          retention-days: 90
      - name: Upload artifact dev
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.exe
          if-no-files-found: error
          retention-days: 4
