name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string
        default: 'v0.0.0'
      rebuild:
        description: 'Rebuild if tag exists'
        required: true
        type: boolean
        default: false

jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: "${{ github.event.inputs.tag }}"
      - name: Stop workflow if tag already exists
        if: ${{ github.event.inputs.rebuild == 'false' && steps.check-tag.outputs.tag-exists == 'true' }}
        run: exit 1
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.8.2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8' 
          cache: 'poetry'
      - name: Install the project dependencies
        run: poetry install
      - name: Downlowd upx
        run: |
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip" -OutFile "upx.zip"
          Expand-Archive -Path "upx.zip" -DestinationPath "."
      - name: Package application for Windows
        run: poetry run pyinstaller --onefile --name=my_app --upx-dir='.\upx-4.2.2-win64' main.py
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.event.inputs.tag }}"
          files: "dist/my_app.exe"
